# Generated by Django 6.0.8 on 2026-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0002_seat_held_by_seat_held_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="offering",
            name="destination",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="offering",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="offering",
            name="origin",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="offering",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="offering",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
