# Generated by Django 6.0.8 on 2026-10-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0003_offering_description_offering_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
