# Generated by Django 6.0.8 on 2026-10-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_waitlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
